=== oDevilo/shadow/src/main/resources/org/devil/shadow/config/tableStrategy-config.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT tableShadow (tableStrategy*)>
<!ELEMENT tableStrategy (name,tables,strategyClass)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT tables (#PCDATA)>
<!ELEMENT strategyClass (#PCDATA)>

=== oDevilo/shadow/shadow-test/src/test/java/org/devil/shadow/test/dynamic/table_strategy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tableShadow PUBLIC "-//shadow.devil.com//DTD tableShadow 2.0//EN"
        "http://shadow.devil.com/dtd/tableStrategy-config.dtd">
<tableShadow>
    <tableStrategy>
        <name>test1</name>
        <tables>test,user</tables>
        <strategyClass>org.devil.shadow.plugTable.TestStra</strategyClass>
    </tableStrategy>
    <tableStrategy>
        <name>test2</name>
        <tables>test2</tables>
        <strategyClass>org.devil.shadow.plugTable.TestStra</strategyClass>
    </tableStrategy>
</tableShadow>
